/** Auto-generated by scripts/sync-windows-manifest.cjs — do not edit. */
export const SITE_WINDOWS_BUILD_MANIFEST = {
  "version": "2026.09.14.01.01",
  "compactVersion": "2026.914.101",
  "releaseTag": "interview-v2026.914.101",
  "installerDownloadUrl": "https://github.com/Shlok0095/VeilAssist/releases/download/interview-v2026.914.101/VeilAssistSetup2026.914.101.exe",
  "portableDownloadUrl": "https://github.com/Shlok0095/VeilAssist/releases/download/interview-v2026.914.101/VeilAssist2026.914.101.exe",
  "builtAt": "2026-09-13T19:37:38.334Z",
  "installerSize": 156468898,
  "portableSize": 156197744,
  "installerSha256": "e0410d6209e8ae21f3d0dd295ac77248fdb762af0d88071e701261c64839e6ca"
} as const
