/** Auto-generated by scripts/sync-windows-manifest.cjs — do not edit. */
export const SITE_WINDOWS_BUILD_MANIFEST = {
  "version": "2026.09.17.00.01",
  "compactVersion": "2026.917.1",
  "releaseTag": "interview-v2026.917.1",
  "installerDownloadUrl": "https://github.com/Shlok0095/VeilAssist/releases/download/interview-v2026.917.1/VeilAssistSetup2026.917.1.exe",
  "portableDownloadUrl": "https://github.com/Shlok0095/VeilAssist/releases/download/interview-v2026.917.1/VeilAssist2026.917.1.exe",
  "builtAt": "2026-09-16T18:55:19.465Z",
  "installerSize": 156478080,
  "portableSize": 156206877,
  "installerSha256": "9736bfd0fc7057da04add8bcb732dc9720463f29517d382e705447c02c19e6e0"
} as const
