/** Auto-generated by scripts/sync-windows-manifest.cjs — do not edit. */
export const SITE_WINDOWS_BUILD_MANIFEST = {
  "version": "2026.09.18.00.01",
  "compactVersion": "2026.918.1",
  "releaseTag": "interview-v2026.918.1",
  "installerDownloadUrl": "https://github.com/Shlok0095/VeilAssist/releases/download/interview-v2026.918.1/VeilAssistSetup2026.918.1.exe",
  "portableDownloadUrl": "https://github.com/Shlok0095/VeilAssist/releases/download/interview-v2026.918.1/VeilAssist2026.918.1.exe",
  "builtAt": "2026-09-17T19:18:20.659Z",
  "installerSize": 156548977,
  "portableSize": 156277786,
  "installerSha256": "aca1078a7effb73985b113174e622dcff9264c9a8806a2f6a416b5371548995b"
} as const
