/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Same contract as `lib/localStt/audioResampler.js` `resampleToF32`:
 * Int16LE mono buffer → Float32 samples at 16 kHz (linear interpolation).
 */
export declare function resampleToF32(chunk: Buffer, inputSampleRate: number): Float32Array
/** Fast RMS of Int16LE PCM (silence heuristics / energy). Returns 0 for empty. */
export declare function pcm16Rms(chunk: Buffer): number
export declare function nativeAudioBackend(): string
